### ISSUE TITLE
Possibility to expose contract API directly

### ISSUE THREAD

**Issue by Kayanski** [AbstractSDK/abstract#246]
I want to create an abstract adapter that respects the CW721 interface (as described here : https://github.com/CosmWasm/cw-nfts/blob/main/packages/cw721/README.md°.

However, I notice that the messages need to be wrapped inside a Module variant. 
``` abstract_core::base::{ExecuteMsg, QueryMsg} ```

Is there a way to expose a cw721 interface within an abstract app or adapter ? And have the messages available as the top level message as well as in the module ?

Thanks !

**Comment by CyberHoward** [comment]
Nope, and this won't be until `#[untagged]` becomes available.

**Comment by Buckram123** [comment]
> I want to create an abstract adapter that respects the CW721 interface (as described here : [https://github.com/CosmWasm/cw-nfts/blob/main/packages/cw721/README.md°](https://github.com/CosmWasm/cw-nfts/blob/main/packages/cw721/README.md%C2%B0).
> 
> However, I notice that the messages need to be wrapped inside a Module variant. `abstract_core::base::{ExecuteMsg, QueryMsg}`
> 
> Is there a way to expose a cw721 interface within an abstract app or adapter ? And have the messages available as the top level message as well as in the module ?
> 
> Thanks !

Should this contract be `standalone` instead of adapter?

**Comment by Kayanski** [comment]
Closing because Standalone contracts works for me there
