### ISSUE TITLE
Sending IBC from an adapter to its counterpart on another chain

### ISSUE THREAD

**Issue by Kayanski** [AbstractSDK/abstract#247]
Does our current Abstract IBC design allow us to send adapter and app messages cross-chain?

Here is my use case : 

- I have 1 adapter per chain on which Abstract is deployed
- I want to be able to send a message from one adapter to another in a permissioned way. I want my remote adapter to be able to trust messages that come from the local adapter.

# Issue

Today ibc messages can only be exchanged by account and not by apps and adapters. This doesn't allow actual interoperability between instances of abstract apps and adapters between chains. 

# Proposed solution

Introduce a new `HostAction` variant that allows adapters and apps to call themselves on other chains

**Comment by CyberHoward** [comment]
They can through the manager contract but it's not efficient. I think I brought this up as an optimization when we were initially implementing the protocol.

**Comment by Kayanski** [comment]
This is solved by https://github.com/AbstractSDK/abstract/commit/65d606ff7bf8158c5e2e51a1de0e60e787dc453a
